all: ./a.out
	gcc file.c
	echo "Não executei por já existe e não houve actualização!"
#all: regra, ./a.out arquivo de dependêcnia se já existe verifica a actualização caso não cria e o comando a seguir!


a.out:
	gcc file.c